apiVersion: v1
kind: Namespace
metadata:
  name: kube-bench
  labels:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/part-of: secure-k8s-platform
    # kube-bench requires hostPID and privileged securityContext to inspect
    # host-level process namespace and filesystem. PSA must be set to
    # 'privileged' to allow these settings in this namespace.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
