apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Chart.Name | quote }}
    app.kubernetes.io/part-of: secure-k8s-delivery-path
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Chart.Name | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

