{{- if .Values.database.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.database.name | quote }}
      app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.database.name | quote }}
        app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy | quote }}
          env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "yes"
            - name: MARIADB_DATABASE
              value: {{ .Values.database.databaseName | quote }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
          {{- if .Values.database.persistence.enabled }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          {{- end }}
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
      {{- if .Values.database.persistence.enabled }}
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-data" .Values.database.name | quote }}
      {{- end }}
{{- if .Values.database.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" .Values.database.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.database.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.database.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride | quote }}
  ports:
    - name: mysql
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
{{- end }}
