apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secure-path-dev
resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
images:
  - name: nginx
    newName: localhost:9092/secure-delivery/simple-web
    newTag: dev
