apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: secure-path-dev
  labels:
    app.kubernetes.io/name: simple-web
    app.kubernetes.io/part-of: secure-k8s-delivery-path
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-web
        app.kubernetes.io/part-of: secure-k8s-delivery-path
    spec:
      containers:
        - name: simple-web
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

