apiVersion: v1
kind: Service
metadata:
  name: simple-web
  namespace: secure-path-dev
  labels:
    app.kubernetes.io/name: simple-web
    app.kubernetes.io/part-of: secure-k8s-delivery-path
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-web
  ports:
    - name: http
      port: 80
      targetPort: 80

